name: SEALWives
favicon: null
layout_spectrum: 0.5663205550517887
typography_spectrum: 0.5114839195739478
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.33344986173324287
  lightness: 0.00144037208519876
  saturation: 0.3024229183793068
  rhythmicContrast: 0.01033025048673153
purpose: []
